Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -13,7 +13,9 @@ jobs:
     steps:
     - uses: actions/checkout@v3
     - name: build 1
-      run: ls /opt/st/stm32cubeide_1.9.0
+      run: |
+        chmod +x /opt/st/stm32cubeide_1.9.0/headless-build.sh
+        ./opt/st/stm32cubeide_1.9.0/headless-build.sh -data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
  #     run: chmod +x /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control/builder.sh
  #   - name: build 2
   #    run: ./workspace/Multichannel-Temperature-Control/builder.sh
