Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -16,13 +16,12 @@ jobs:
         echo ${{ github.workspace }}
         pwd
         ls -la 
-        ls -la ${{ github.workspace }}
         ls -la /opt/st/stm32cubeide_1.9.0
     - name: build 1
       run: |
         chmod +x /opt/st/stm32cubeide_1.9.0/headless-build.sh
         cd /opt/st/stm32cubeide_1.9.0
-        ./headless-build.sh -data /workspace -import ${{ github.workspace }} -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
+        ./headless-build.sh -data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
 #    - name: build 2
 #      run: ./opt/st/stm32cubeide_1.9.0/headless-build.sh
       #-data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
